# Copyright (C) 2024 Bellande Robotics Sensors Research Innovation Center, Ronaldson Bellande
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
version: '3.8'

services:
  ros1:
    build:
      context: ../docker
      dockerfile: Dockerfile.ros1
    image: bellande_humanoid_robotic_ros1_simple_demo
    depends_on:
      - vpn
      - web-api
    environment:
      - ROS_DISTRO=noetic

  vpn:
    image: ronaldsonbellande/bellande_robotic_vpn
    
  web-api:
    image: ronaldsonbellande/bellande_web_api_packages_ros1

volumes:
  ros-data:
