name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_ros1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image ROS1
      run: docker build . --file ./docker/Dockerfile.ros1 --tag my-image-name:$(date +%s)

  build_ros2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image ROS2
      run: docker build . --file ./docker/Dockerfile.ros1 --tag my-image-name:$(date +%s)
